"""Add phone

Revision ID: 433d5a89ffd0
Revises: 115f108cad25
Create Date: 2022-09-18 18:44:03.097857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433d5a89ffd0'
down_revision = '115f108cad25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
